[Build]
ToolsTree=default
ToolsTreeDistribution=fedora
ToolsTreeRelease=44

[Content]
Packages=systemd-pam
         sudo
         shadow-utils
         tzdata
         ca-certificates
         openssh-server
         dejavu-sans-fonts
         adwaita-cursor-theme
         libwayland-client
         libwayland-cursor
