[Distribution]
RepositoryKeyFetch=yes

[Content]
Packages=openssh-server
         ca-certificates
         systemd-ukify
         dracut
         python3
         sudo
         shadow-utils
         waypipe
         curl
         e2fsprogs
         selinux-policy-targeted
         policycoreutils
SELinuxRelabel=yes
