[Distribution]
RepositoryKeyFetch=yes

[Content]
Packages=openssh-server
         ca-certificates-mozilla
         systemd-boot
         systemd-resolved
         systemd-experimental
         python3-pefile
         dracut
         python3
         sudo
         shadow
         waypipe
         curl
         btrfsprogs
         selinux-policy-targeted
         container-selinux
         policycoreutils
SELinuxRelabel=yes
