# SPDX-License-Identifier: LGPL-2.1-or-later
# Derived from nspawn/mkosi-definitions' disk profile. Keep dpkg's /boot
# kernel files on btrfs; only firmware boot files belong on the ESP.
[Partition]
Type=esp
Format=vfat
CopyFiles=/boot/EFI:/EFI
CopyFiles=/boot/loader:/loader
CopyFiles=/efi:/
MountPoint=/efi
SizeMinBytes=1G
SizeMaxBytes=1G
