[Content]
Packages=initramfs-tools
         udev
         openssh-server
         ca-certificates
         systemd-repart
         systemd-boot-efi
         systemd-ukify
         apparmor
         apparmor-utils
         zstd
         python3
         sudo
         dbus-user-session
         libpam-systemd
         waypipe
         galculator
         curl
         e2fsprogs
