[Distribution]
RepositoryKeyFetch=yes

[Content]
Packages=openssh-server
         ca-certificates
         systemd-ukify
         systemd-pam
         dracut
         python3
         sudo
         shadow-utils
         waypipe
         galculator
         curl
         btrfs-progs
         selinux-policy-targeted
         policycoreutils
SELinuxRelabel=yes
