#!/usr/bin/env python3
"""Collect shipped Go package licenses and notices from the pinned module graph."""
import argparse
import json
import os
from pathlib import Path
import subprocess

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT/'THIRD_PARTY_NOTICES.txt'


def go(*args, architecture=None):
    env = os.environ.copy()
    if architecture:
        env.update(GOOS='linux', GOARCH=architecture, CGO_ENABLED='0')
    return subprocess.run(['go', *args], cwd=ROOT, env=env, capture_output=True, text=True, check=True).stdout


def generate():
    stream = '\n'.join(go('list', '-deps', '-json', '.', architecture=arch) for arch in ('amd64', 'arm64'))
    decoder = json.JSONDecoder()
    records = {}
    while stream.strip():
        stream = stream.lstrip()
        package, offset = decoder.raw_decode(stream)
        stream = stream[offset:]
        module = package.get('Module')
        if not module or module.get('Main'):
            continue
        root = Path(module['Dir'])
        directory = Path(package['Dir'])
        found = False
        for parent in (directory, *directory.parents):
            if parent != root and root not in parent.parents:
                break
            for path in sorted(parent.iterdir()):
                name = path.name.upper()
                if path.is_file() and (name.startswith('LICENSE') or name.startswith('NOTICE') or name in ('COPYING', 'COPYRIGHT')):
                    key = module['Path']+' '+module['Version']+' / '+str(path.relative_to(root))
                    records[key] = path.read_text()
                    found = True
            if parent == root:
                break
        if not found:
            raise ValueError('missing license for runtime dependency '+package['ImportPath'])
    records['Go standard library / LICENSE'] = (Path(go('env', 'GOROOT').strip())/'LICENSE').read_text()
    result = 'Third-party notices for the nsl CLI\n\nGenerated by scripts/license-notices.py from the runtime Go module graph.\nThe nsl integration itself is covered by LICENSE. Guest distribution packages\ncarry their own licenses; the published inventory identifies resolved versions.\n'
    for name, content in sorted(records.items()):
        result += '\n'+'='*78+'\n'+name+'\n'+'='*78+'\n\n'+content.rstrip()+'\n'
    return result


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    content = generate()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text() != content:
            raise SystemExit('Run python3 scripts/license-notices.py after changing Go dependencies.')
    else:
        OUTPUT.write_text(content)


if __name__ == '__main__':
    main()
