[Build]
ToolsTree=no
Incremental=no

[Content]
RootPassword=hashed:!
Ssh=never
ExtraTrees=overlay
PostInstallationScripts=nsl-postinst.chroot
FinalizeScripts=nsl-finalize.chroot
Packages=openssh-server
         ca-certificates
         dbus
         systemd-repart
         systemd-boot-efi
         systemd-ukify
         systemd-container
         btrfs-progs
         zstd
         waypipe
