[Distribution]
RepositoryKeyFetch=yes
Snapshot=2026/09/25

[Content]
Packages=openssh
         ca-certificates
         systemd-ukify
         dracut
         python
         sudo
         shadow
         waypipe
         curl
         btrfs-progs
