[Distribution]
RepositoryKeyFetch=yes
Snapshot=20260923

[Content]
Packages=openssh-server
         ca-certificates-mozilla
         systemd-boot
         systemd-resolved
         systemd-experimental
         systemd-ukify
         dracut
         python3
         sudo
         shadow
         waypipe
         curl
         btrfsprogs
         selinux-policy-targeted
         policycoreutils
SELinuxRelabel=yes
