[Build]
ToolsTree=no
Incremental=no

[Output]
Output=nsl-debian-v4
ImageId=nsl-debian

[Content]
RootPassword=hashed:!
Ssh=never
Packages=openssh-server
         ca-certificates
         systemd-repart
         systemd-boot-efi
         systemd-ukify
         zstd
         python3
         sudo
         dbus-user-session
         libpam-systemd
         waypipe
         galculator
         curl
         btrfs-progs
ExtraTrees=overlay
PostInstallationScripts=nsl-postinst.chroot
